# Generated by Django 3.1.5 on 2021-01-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablist',
            name='_db_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
