# Generated by Django 3.1.5 on 2021-01-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablist',
            old_name='to_study',
            new_name='study',
        ),
    ]
