# Generated by Django 3.1.5 on 2021-01-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0002_auto_20210128_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablist',
            name='sid',
        ),
    ]
