# Generated by Django 3.1.5 on 2021-01-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0002_auto_20210122_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named_id', models.CharField(db_index=True, max_length=50)),
                ('artist', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('note', models.CharField(db_index=True, max_length=255)),
                ('count', models.IntegerField()),
                ('chords', models.CharField(db_index=True, max_length=255)),
                ('chords_filename', models.CharField(db_index=True, max_length=255)),
                ('pattern', models.CharField(db_index=True, max_length=255)),
                ('fpath', models.CharField(db_index=True, max_length=255)),
                ('ftype', models.CharField(db_index=True, max_length=25)),
                ('page', models.CharField(db_index=True, max_length=25)),
                ('filecomment', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
