# Generated by Django 3.1.5 on 2021-01-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0002_auto_20210128_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablist',
            old_name='_artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='tablist',
            old_name='_chords',
            new_name='chords',
        ),
        migrations.RenameField(
            model_name='tablist',
            old_name='_count',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='tablist',
            old_name='_db',
            new_name='db',
        ),
        migrations.RenameField(
            model_name='tablist',
            old_name='_db_name',
            new_name='db_name',
        ),
        migrations.RenameField(
            model_name='tablist',
            old_name='_rank',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='tablist',
            old_name='_id',
            new_name='sid',
        ),
        migrations.RenameField(
            model_name='tablist',
            old_name='_songbook',
            new_name='songbook',
        ),
        migrations.RenameField(
            model_name='tablist',
            old_name='_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tablist',
            old_name='_to_study',
            new_name='to_study',
        ),
        migrations.RenameField(
            model_name='tablist',
            old_name='_type',
            new_name='type',
        ),
    ]
